//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTGN.ImportFromDeckbox {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OCTGN.ImportFromDeckbox.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin was written by Michael Wagner. Use the OCTGN foum to report issues and feature requests..
        /// </summary>
        public static string AboutboxAuthor {
            get {
                return ResourceManager.GetString("AboutboxAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version History.
        /// </summary>
        public static string AboutboxHeader {
            get {
                return ResourceManager.GetString("AboutboxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Profit Open Software License 3.0 (NPOSL-3.0)
        ///
        ///This Non-Profit Open Software License (“Non-Profit OSL”) version 3.0 (the “License”) applies to any original work of authorship (the “Original Work”) whose owner (the “Licensor”) has placed the following licensing notice adjacent to the copyright notice for the Original Work:
        ///
        ///Licensed under the Non-Profit Open Software License version 3.0
        ///
        ///1) Grant of Copyright License. Licensor grants You a worldwide, royalty-free, non-exclusive, sublicensable licens [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutboxLicence {
            get {
                return ResourceManager.GetString("AboutboxLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin is published under the NPOSL-3.0:.
        /// </summary>
        public static string AboutboxLicenceHeader {
            get {
                return ResourceManager.GetString("AboutboxLicenceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Deckbox Import Plugin.
        /// </summary>
        public static string AboutboxTitle {
            get {
                return ResourceManager.GetString("AboutboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string AboutboxVersionHeaderDetails {
            get {
                return ResourceManager.GetString("AboutboxVersionHeaderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version number.
        /// </summary>
        public static string AboutboxVersionHeaderVersion {
            get {
                return ResourceManager.GetString("AboutboxVersionHeaderVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating Important Stuff....
        /// </summary>
        public static string BusyText {
            get {
                return ResourceManager.GetString("BusyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        public static string ButtonAbout {
            get {
                return ResourceManager.GetString("ButtonAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse and Save Deck.
        /// </summary>
        public static string ButtonParseAndSave {
            get {
                return ResourceManager.GetString("ButtonParseAndSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Deckbox.org Deck from Clipboard.
        /// </summary>
        public static string ButtonPaste {
            get {
                return ResourceManager.GetString("ButtonPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Deck 4 Forum.
        /// </summary>
        public static string CopyForum {
            get {
                return ResourceManager.GetString("CopyForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find cards:.
        /// </summary>
        public static string ErrorCannotFindCards {
            get {
                return ResourceManager.GetString("ErrorCannotFindCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing text content..
        /// </summary>
        public static string ErrorHintParseError {
            get {
                return ResourceManager.GetString("ErrorHintParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Create your deck list on deckbox.org.
        ///2. Click on View-&gt;Print to display the print version of your deck.
        ///3. Copy the complete text of this print view into the text field below.
        ///4. The found cards will be displayed in the list below on the right side..
        /// </summary>
        public static string ExplenationParse {
            get {
                return ResourceManager.GetString("ExplenationParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [b]Deck summary: [/b].
        /// </summary>
        public static string ForumDeckSummary {
            get {
                return ResourceManager.GetString("ForumDeckSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Deckbox Deck List.
        /// </summary>
        public static string GroupBoxHeaderDeckbox {
            get {
                return ResourceManager.GetString("GroupBoxHeaderDeckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital:.
        /// </summary>
        public static string LabelCapital {
            get {
                return ResourceManager.GetString("LabelCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded Cards:.
        /// </summary>
        public static string LoadedCards {
            get {
                return ResourceManager.GetString("LoadedCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched Cards:.
        /// </summary>
        public static string MatchedCards {
            get {
                return ResourceManager.GetString("MatchedCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Cards ({1} Distinct).
        /// </summary>
        public static string MatchedCardSummary {
            get {
                return ResourceManager.GetString("MatchedCardSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed Cards:.
        /// </summary>
        public static string ParsedCards {
            get {
                return ResourceManager.GetString("ParsedCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General parse error: Cannot find any cards..
        /// </summary>
        public static string ParseErrorGeneral {
            get {
                return ResourceManager.GetString("ParseErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing mismatch: Found {0} card count values but {1} card names..
        /// </summary>
        public static string ParseErrorLineMismatch {
            get {
                return ResourceManager.GetString("ParseErrorLineMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Deckbox.org.
        /// </summary>
        public static string PluginMenuItem {
            get {
                return ResourceManager.GetString("PluginMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Deck from Deckbox.org Plugin.
        /// </summary>
        public static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Game.
        /// </summary>
        public static string SelectGame {
            get {
                return ResourceManager.GetString("SelectGame", resourceCulture);
            }
        }
    }
}
